//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: sui/rpc/v2/move_package_service.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Sui_Rpc_V2_MovePackageServiceClient`, then call methods of this protocol to make API calls.
internal protocol Sui_Rpc_V2_MovePackageServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Sui_Rpc_V2_MovePackageServiceClientInterceptorFactoryProtocol? { get }

  func getPackage(
    _ request: Sui_Rpc_V2_GetPackageRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sui_Rpc_V2_GetPackageRequest, Sui_Rpc_V2_GetPackageResponse>

  func getDatatype(
    _ request: Sui_Rpc_V2_GetDatatypeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sui_Rpc_V2_GetDatatypeRequest, Sui_Rpc_V2_GetDatatypeResponse>

  func getFunction(
    _ request: Sui_Rpc_V2_GetFunctionRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sui_Rpc_V2_GetFunctionRequest, Sui_Rpc_V2_GetFunctionResponse>

  func listPackageVersions(
    _ request: Sui_Rpc_V2_ListPackageVersionsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sui_Rpc_V2_ListPackageVersionsRequest, Sui_Rpc_V2_ListPackageVersionsResponse>
}

extension Sui_Rpc_V2_MovePackageServiceClientProtocol {
  internal var serviceName: String {
    return "sui.rpc.v2.MovePackageService"
  }

  /// Unary call to GetPackage
  ///
  /// - Parameters:
  ///   - request: Request to send to GetPackage.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getPackage(
    _ request: Sui_Rpc_V2_GetPackageRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sui_Rpc_V2_GetPackageRequest, Sui_Rpc_V2_GetPackageResponse> {
    return self.makeUnaryCall(
      path: Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.getPackage.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPackageInterceptors() ?? []
    )
  }

  /// Unary call to GetDatatype
  ///
  /// - Parameters:
  ///   - request: Request to send to GetDatatype.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getDatatype(
    _ request: Sui_Rpc_V2_GetDatatypeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sui_Rpc_V2_GetDatatypeRequest, Sui_Rpc_V2_GetDatatypeResponse> {
    return self.makeUnaryCall(
      path: Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.getDatatype.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetDatatypeInterceptors() ?? []
    )
  }

  /// Unary call to GetFunction
  ///
  /// - Parameters:
  ///   - request: Request to send to GetFunction.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getFunction(
    _ request: Sui_Rpc_V2_GetFunctionRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sui_Rpc_V2_GetFunctionRequest, Sui_Rpc_V2_GetFunctionResponse> {
    return self.makeUnaryCall(
      path: Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.getFunction.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFunctionInterceptors() ?? []
    )
  }

  /// Unary call to ListPackageVersions
  ///
  /// - Parameters:
  ///   - request: Request to send to ListPackageVersions.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listPackageVersions(
    _ request: Sui_Rpc_V2_ListPackageVersionsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sui_Rpc_V2_ListPackageVersionsRequest, Sui_Rpc_V2_ListPackageVersionsResponse> {
    return self.makeUnaryCall(
      path: Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.listPackageVersions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListPackageVersionsInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Sui_Rpc_V2_MovePackageServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Sui_Rpc_V2_MovePackageServiceNIOClient")
internal final class Sui_Rpc_V2_MovePackageServiceClient: Sui_Rpc_V2_MovePackageServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Sui_Rpc_V2_MovePackageServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Sui_Rpc_V2_MovePackageServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the sui.rpc.v2.MovePackageService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sui_Rpc_V2_MovePackageServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Sui_Rpc_V2_MovePackageServiceNIOClient: Sui_Rpc_V2_MovePackageServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sui_Rpc_V2_MovePackageServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the sui.rpc.v2.MovePackageService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sui_Rpc_V2_MovePackageServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sui_Rpc_V2_MovePackageServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sui_Rpc_V2_MovePackageServiceClientInterceptorFactoryProtocol? { get }

  func makeGetPackageCall(
    _ request: Sui_Rpc_V2_GetPackageRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sui_Rpc_V2_GetPackageRequest, Sui_Rpc_V2_GetPackageResponse>

  func makeGetDatatypeCall(
    _ request: Sui_Rpc_V2_GetDatatypeRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sui_Rpc_V2_GetDatatypeRequest, Sui_Rpc_V2_GetDatatypeResponse>

  func makeGetFunctionCall(
    _ request: Sui_Rpc_V2_GetFunctionRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sui_Rpc_V2_GetFunctionRequest, Sui_Rpc_V2_GetFunctionResponse>

  func makeListPackageVersionsCall(
    _ request: Sui_Rpc_V2_ListPackageVersionsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Sui_Rpc_V2_ListPackageVersionsRequest, Sui_Rpc_V2_ListPackageVersionsResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sui_Rpc_V2_MovePackageServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sui_Rpc_V2_MovePackageServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Sui_Rpc_V2_MovePackageServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeGetPackageCall(
    _ request: Sui_Rpc_V2_GetPackageRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sui_Rpc_V2_GetPackageRequest, Sui_Rpc_V2_GetPackageResponse> {
    return self.makeAsyncUnaryCall(
      path: Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.getPackage.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPackageInterceptors() ?? []
    )
  }

  internal func makeGetDatatypeCall(
    _ request: Sui_Rpc_V2_GetDatatypeRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sui_Rpc_V2_GetDatatypeRequest, Sui_Rpc_V2_GetDatatypeResponse> {
    return self.makeAsyncUnaryCall(
      path: Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.getDatatype.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetDatatypeInterceptors() ?? []
    )
  }

  internal func makeGetFunctionCall(
    _ request: Sui_Rpc_V2_GetFunctionRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sui_Rpc_V2_GetFunctionRequest, Sui_Rpc_V2_GetFunctionResponse> {
    return self.makeAsyncUnaryCall(
      path: Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.getFunction.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFunctionInterceptors() ?? []
    )
  }

  internal func makeListPackageVersionsCall(
    _ request: Sui_Rpc_V2_ListPackageVersionsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Sui_Rpc_V2_ListPackageVersionsRequest, Sui_Rpc_V2_ListPackageVersionsResponse> {
    return self.makeAsyncUnaryCall(
      path: Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.listPackageVersions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListPackageVersionsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sui_Rpc_V2_MovePackageServiceAsyncClientProtocol {
  internal func getPackage(
    _ request: Sui_Rpc_V2_GetPackageRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sui_Rpc_V2_GetPackageResponse {
    return try await self.performAsyncUnaryCall(
      path: Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.getPackage.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPackageInterceptors() ?? []
    )
  }

  internal func getDatatype(
    _ request: Sui_Rpc_V2_GetDatatypeRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sui_Rpc_V2_GetDatatypeResponse {
    return try await self.performAsyncUnaryCall(
      path: Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.getDatatype.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetDatatypeInterceptors() ?? []
    )
  }

  internal func getFunction(
    _ request: Sui_Rpc_V2_GetFunctionRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sui_Rpc_V2_GetFunctionResponse {
    return try await self.performAsyncUnaryCall(
      path: Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.getFunction.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFunctionInterceptors() ?? []
    )
  }

  internal func listPackageVersions(
    _ request: Sui_Rpc_V2_ListPackageVersionsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Sui_Rpc_V2_ListPackageVersionsResponse {
    return try await self.performAsyncUnaryCall(
      path: Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.listPackageVersions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListPackageVersionsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Sui_Rpc_V2_MovePackageServiceAsyncClient: Sui_Rpc_V2_MovePackageServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sui_Rpc_V2_MovePackageServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sui_Rpc_V2_MovePackageServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Sui_Rpc_V2_MovePackageServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getPackage'.
  func makeGetPackageInterceptors() -> [ClientInterceptor<Sui_Rpc_V2_GetPackageRequest, Sui_Rpc_V2_GetPackageResponse>]

  /// - Returns: Interceptors to use when invoking 'getDatatype'.
  func makeGetDatatypeInterceptors() -> [ClientInterceptor<Sui_Rpc_V2_GetDatatypeRequest, Sui_Rpc_V2_GetDatatypeResponse>]

  /// - Returns: Interceptors to use when invoking 'getFunction'.
  func makeGetFunctionInterceptors() -> [ClientInterceptor<Sui_Rpc_V2_GetFunctionRequest, Sui_Rpc_V2_GetFunctionResponse>]

  /// - Returns: Interceptors to use when invoking 'listPackageVersions'.
  func makeListPackageVersionsInterceptors() -> [ClientInterceptor<Sui_Rpc_V2_ListPackageVersionsRequest, Sui_Rpc_V2_ListPackageVersionsResponse>]
}

internal enum Sui_Rpc_V2_MovePackageServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MovePackageService",
    fullName: "sui.rpc.v2.MovePackageService",
    methods: [
      Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.getPackage,
      Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.getDatatype,
      Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.getFunction,
      Sui_Rpc_V2_MovePackageServiceClientMetadata.Methods.listPackageVersions,
    ]
  )

  internal enum Methods {
    internal static let getPackage = GRPCMethodDescriptor(
      name: "GetPackage",
      path: "/sui.rpc.v2.MovePackageService/GetPackage",
      type: GRPCCallType.unary
    )

    internal static let getDatatype = GRPCMethodDescriptor(
      name: "GetDatatype",
      path: "/sui.rpc.v2.MovePackageService/GetDatatype",
      type: GRPCCallType.unary
    )

    internal static let getFunction = GRPCMethodDescriptor(
      name: "GetFunction",
      path: "/sui.rpc.v2.MovePackageService/GetFunction",
      type: GRPCCallType.unary
    )

    internal static let listPackageVersions = GRPCMethodDescriptor(
      name: "ListPackageVersions",
      path: "/sui.rpc.v2.MovePackageService/ListPackageVersions",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Sui_Rpc_V2_MovePackageServiceProvider: CallHandlerProvider {
  var interceptors: Sui_Rpc_V2_MovePackageServiceServerInterceptorFactoryProtocol? { get }

  func getPackage(request: Sui_Rpc_V2_GetPackageRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sui_Rpc_V2_GetPackageResponse>

  func getDatatype(request: Sui_Rpc_V2_GetDatatypeRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sui_Rpc_V2_GetDatatypeResponse>

  func getFunction(request: Sui_Rpc_V2_GetFunctionRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sui_Rpc_V2_GetFunctionResponse>

  func listPackageVersions(request: Sui_Rpc_V2_ListPackageVersionsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sui_Rpc_V2_ListPackageVersionsResponse>
}

extension Sui_Rpc_V2_MovePackageServiceProvider {
  internal var serviceName: Substring {
    return Sui_Rpc_V2_MovePackageServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetPackage":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sui_Rpc_V2_GetPackageRequest>(),
        responseSerializer: ProtobufSerializer<Sui_Rpc_V2_GetPackageResponse>(),
        interceptors: self.interceptors?.makeGetPackageInterceptors() ?? [],
        userFunction: self.getPackage(request:context:)
      )

    case "GetDatatype":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sui_Rpc_V2_GetDatatypeRequest>(),
        responseSerializer: ProtobufSerializer<Sui_Rpc_V2_GetDatatypeResponse>(),
        interceptors: self.interceptors?.makeGetDatatypeInterceptors() ?? [],
        userFunction: self.getDatatype(request:context:)
      )

    case "GetFunction":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sui_Rpc_V2_GetFunctionRequest>(),
        responseSerializer: ProtobufSerializer<Sui_Rpc_V2_GetFunctionResponse>(),
        interceptors: self.interceptors?.makeGetFunctionInterceptors() ?? [],
        userFunction: self.getFunction(request:context:)
      )

    case "ListPackageVersions":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sui_Rpc_V2_ListPackageVersionsRequest>(),
        responseSerializer: ProtobufSerializer<Sui_Rpc_V2_ListPackageVersionsResponse>(),
        interceptors: self.interceptors?.makeListPackageVersionsInterceptors() ?? [],
        userFunction: self.listPackageVersions(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Sui_Rpc_V2_MovePackageServiceAsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Sui_Rpc_V2_MovePackageServiceServerInterceptorFactoryProtocol? { get }

  @Sendable func getPackage(
    request: Sui_Rpc_V2_GetPackageRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sui_Rpc_V2_GetPackageResponse

  @Sendable func getDatatype(
    request: Sui_Rpc_V2_GetDatatypeRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sui_Rpc_V2_GetDatatypeResponse

  @Sendable func getFunction(
    request: Sui_Rpc_V2_GetFunctionRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sui_Rpc_V2_GetFunctionResponse

  @Sendable func listPackageVersions(
    request: Sui_Rpc_V2_ListPackageVersionsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Sui_Rpc_V2_ListPackageVersionsResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Sui_Rpc_V2_MovePackageServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Sui_Rpc_V2_MovePackageServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Sui_Rpc_V2_MovePackageServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Sui_Rpc_V2_MovePackageServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetPackage":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sui_Rpc_V2_GetPackageRequest>(),
        responseSerializer: ProtobufSerializer<Sui_Rpc_V2_GetPackageResponse>(),
        interceptors: self.interceptors?.makeGetPackageInterceptors() ?? [],
        wrapping: self.getPackage(request:context:)
      )

    case "GetDatatype":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sui_Rpc_V2_GetDatatypeRequest>(),
        responseSerializer: ProtobufSerializer<Sui_Rpc_V2_GetDatatypeResponse>(),
        interceptors: self.interceptors?.makeGetDatatypeInterceptors() ?? [],
        wrapping: self.getDatatype(request:context:)
      )

    case "GetFunction":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sui_Rpc_V2_GetFunctionRequest>(),
        responseSerializer: ProtobufSerializer<Sui_Rpc_V2_GetFunctionResponse>(),
        interceptors: self.interceptors?.makeGetFunctionInterceptors() ?? [],
        wrapping: self.getFunction(request:context:)
      )

    case "ListPackageVersions":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sui_Rpc_V2_ListPackageVersionsRequest>(),
        responseSerializer: ProtobufSerializer<Sui_Rpc_V2_ListPackageVersionsResponse>(),
        interceptors: self.interceptors?.makeListPackageVersionsInterceptors() ?? [],
        wrapping: self.listPackageVersions(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Sui_Rpc_V2_MovePackageServiceServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'getPackage'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetPackageInterceptors() -> [ServerInterceptor<Sui_Rpc_V2_GetPackageRequest, Sui_Rpc_V2_GetPackageResponse>]

  /// - Returns: Interceptors to use when handling 'getDatatype'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetDatatypeInterceptors() -> [ServerInterceptor<Sui_Rpc_V2_GetDatatypeRequest, Sui_Rpc_V2_GetDatatypeResponse>]

  /// - Returns: Interceptors to use when handling 'getFunction'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetFunctionInterceptors() -> [ServerInterceptor<Sui_Rpc_V2_GetFunctionRequest, Sui_Rpc_V2_GetFunctionResponse>]

  /// - Returns: Interceptors to use when handling 'listPackageVersions'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListPackageVersionsInterceptors() -> [ServerInterceptor<Sui_Rpc_V2_ListPackageVersionsRequest, Sui_Rpc_V2_ListPackageVersionsResponse>]
}

internal enum Sui_Rpc_V2_MovePackageServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "MovePackageService",
    fullName: "sui.rpc.v2.MovePackageService",
    methods: [
      Sui_Rpc_V2_MovePackageServiceServerMetadata.Methods.getPackage,
      Sui_Rpc_V2_MovePackageServiceServerMetadata.Methods.getDatatype,
      Sui_Rpc_V2_MovePackageServiceServerMetadata.Methods.getFunction,
      Sui_Rpc_V2_MovePackageServiceServerMetadata.Methods.listPackageVersions,
    ]
  )

  internal enum Methods {
    internal static let getPackage = GRPCMethodDescriptor(
      name: "GetPackage",
      path: "/sui.rpc.v2.MovePackageService/GetPackage",
      type: GRPCCallType.unary
    )

    internal static let getDatatype = GRPCMethodDescriptor(
      name: "GetDatatype",
      path: "/sui.rpc.v2.MovePackageService/GetDatatype",
      type: GRPCCallType.unary
    )

    internal static let getFunction = GRPCMethodDescriptor(
      name: "GetFunction",
      path: "/sui.rpc.v2.MovePackageService/GetFunction",
      type: GRPCCallType.unary
    )

    internal static let listPackageVersions = GRPCMethodDescriptor(
      name: "ListPackageVersions",
      path: "/sui.rpc.v2.MovePackageService/ListPackageVersions",
      type: GRPCCallType.unary
    )
  }
}
