//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: injective/wasmx/v1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Query defines the gRPC querier service.
///
/// Usage: instantiate `Injective_Wasmx_V1_QueryClient`, then call methods of this protocol to make API calls.
internal protocol Injective_Wasmx_V1_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Injective_Wasmx_V1_QueryClientInterceptorFactoryProtocol? { get }

  func wasmxParams(
    _ request: Injective_Wasmx_V1_QueryWasmxParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Injective_Wasmx_V1_QueryWasmxParamsRequest, Injective_Wasmx_V1_QueryWasmxParamsResponse>

  func contractRegistrationInfo(
    _ request: Injective_Wasmx_V1_QueryContractRegistrationInfoRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Injective_Wasmx_V1_QueryContractRegistrationInfoRequest, Injective_Wasmx_V1_QueryContractRegistrationInfoResponse>

  func wasmxModuleState(
    _ request: Injective_Wasmx_V1_QueryModuleStateRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Injective_Wasmx_V1_QueryModuleStateRequest, Injective_Wasmx_V1_QueryModuleStateResponse>
}

extension Injective_Wasmx_V1_QueryClientProtocol {
  internal var serviceName: String {
    return "injective.wasmx.v1.Query"
  }

  /// Retrieves wasmx params
  ///
  /// - Parameters:
  ///   - request: Request to send to WasmxParams.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func wasmxParams(
    _ request: Injective_Wasmx_V1_QueryWasmxParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Injective_Wasmx_V1_QueryWasmxParamsRequest, Injective_Wasmx_V1_QueryWasmxParamsResponse> {
    return self.makeUnaryCall(
      path: Injective_Wasmx_V1_QueryClientMetadata.Methods.wasmxParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWasmxParamsInterceptors() ?? []
    )
  }

  /// Retrieves contract registration info
  ///
  /// - Parameters:
  ///   - request: Request to send to ContractRegistrationInfo.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func contractRegistrationInfo(
    _ request: Injective_Wasmx_V1_QueryContractRegistrationInfoRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Injective_Wasmx_V1_QueryContractRegistrationInfoRequest, Injective_Wasmx_V1_QueryContractRegistrationInfoResponse> {
    return self.makeUnaryCall(
      path: Injective_Wasmx_V1_QueryClientMetadata.Methods.contractRegistrationInfo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeContractRegistrationInfoInterceptors() ?? []
    )
  }

  /// Retrieves the entire wasmx module's state
  ///
  /// - Parameters:
  ///   - request: Request to send to WasmxModuleState.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func wasmxModuleState(
    _ request: Injective_Wasmx_V1_QueryModuleStateRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Injective_Wasmx_V1_QueryModuleStateRequest, Injective_Wasmx_V1_QueryModuleStateResponse> {
    return self.makeUnaryCall(
      path: Injective_Wasmx_V1_QueryClientMetadata.Methods.wasmxModuleState.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWasmxModuleStateInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Injective_Wasmx_V1_QueryClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Injective_Wasmx_V1_QueryNIOClient")
internal final class Injective_Wasmx_V1_QueryClient: Injective_Wasmx_V1_QueryClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Injective_Wasmx_V1_QueryClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Injective_Wasmx_V1_QueryClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the injective.wasmx.v1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Injective_Wasmx_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Injective_Wasmx_V1_QueryNIOClient: Injective_Wasmx_V1_QueryClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Injective_Wasmx_V1_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the injective.wasmx.v1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Injective_Wasmx_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Query defines the gRPC querier service.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Injective_Wasmx_V1_QueryAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Injective_Wasmx_V1_QueryClientInterceptorFactoryProtocol? { get }

  func makeWasmxParamsCall(
    _ request: Injective_Wasmx_V1_QueryWasmxParamsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Injective_Wasmx_V1_QueryWasmxParamsRequest, Injective_Wasmx_V1_QueryWasmxParamsResponse>

  func makeContractRegistrationInfoCall(
    _ request: Injective_Wasmx_V1_QueryContractRegistrationInfoRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Injective_Wasmx_V1_QueryContractRegistrationInfoRequest, Injective_Wasmx_V1_QueryContractRegistrationInfoResponse>

  func makeWasmxModuleStateCall(
    _ request: Injective_Wasmx_V1_QueryModuleStateRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Injective_Wasmx_V1_QueryModuleStateRequest, Injective_Wasmx_V1_QueryModuleStateResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Injective_Wasmx_V1_QueryAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Injective_Wasmx_V1_QueryClientMetadata.serviceDescriptor
  }

  internal var interceptors: Injective_Wasmx_V1_QueryClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeWasmxParamsCall(
    _ request: Injective_Wasmx_V1_QueryWasmxParamsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Injective_Wasmx_V1_QueryWasmxParamsRequest, Injective_Wasmx_V1_QueryWasmxParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Injective_Wasmx_V1_QueryClientMetadata.Methods.wasmxParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWasmxParamsInterceptors() ?? []
    )
  }

  internal func makeContractRegistrationInfoCall(
    _ request: Injective_Wasmx_V1_QueryContractRegistrationInfoRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Injective_Wasmx_V1_QueryContractRegistrationInfoRequest, Injective_Wasmx_V1_QueryContractRegistrationInfoResponse> {
    return self.makeAsyncUnaryCall(
      path: Injective_Wasmx_V1_QueryClientMetadata.Methods.contractRegistrationInfo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeContractRegistrationInfoInterceptors() ?? []
    )
  }

  internal func makeWasmxModuleStateCall(
    _ request: Injective_Wasmx_V1_QueryModuleStateRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Injective_Wasmx_V1_QueryModuleStateRequest, Injective_Wasmx_V1_QueryModuleStateResponse> {
    return self.makeAsyncUnaryCall(
      path: Injective_Wasmx_V1_QueryClientMetadata.Methods.wasmxModuleState.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWasmxModuleStateInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Injective_Wasmx_V1_QueryAsyncClientProtocol {
  internal func wasmxParams(
    _ request: Injective_Wasmx_V1_QueryWasmxParamsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Injective_Wasmx_V1_QueryWasmxParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Injective_Wasmx_V1_QueryClientMetadata.Methods.wasmxParams.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWasmxParamsInterceptors() ?? []
    )
  }

  internal func contractRegistrationInfo(
    _ request: Injective_Wasmx_V1_QueryContractRegistrationInfoRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Injective_Wasmx_V1_QueryContractRegistrationInfoResponse {
    return try await self.performAsyncUnaryCall(
      path: Injective_Wasmx_V1_QueryClientMetadata.Methods.contractRegistrationInfo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeContractRegistrationInfoInterceptors() ?? []
    )
  }

  internal func wasmxModuleState(
    _ request: Injective_Wasmx_V1_QueryModuleStateRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Injective_Wasmx_V1_QueryModuleStateResponse {
    return try await self.performAsyncUnaryCall(
      path: Injective_Wasmx_V1_QueryClientMetadata.Methods.wasmxModuleState.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeWasmxModuleStateInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Injective_Wasmx_V1_QueryAsyncClient: Injective_Wasmx_V1_QueryAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Injective_Wasmx_V1_QueryClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Injective_Wasmx_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Injective_Wasmx_V1_QueryClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'wasmxParams'.
  func makeWasmxParamsInterceptors() -> [ClientInterceptor<Injective_Wasmx_V1_QueryWasmxParamsRequest, Injective_Wasmx_V1_QueryWasmxParamsResponse>]

  /// - Returns: Interceptors to use when invoking 'contractRegistrationInfo'.
  func makeContractRegistrationInfoInterceptors() -> [ClientInterceptor<Injective_Wasmx_V1_QueryContractRegistrationInfoRequest, Injective_Wasmx_V1_QueryContractRegistrationInfoResponse>]

  /// - Returns: Interceptors to use when invoking 'wasmxModuleState'.
  func makeWasmxModuleStateInterceptors() -> [ClientInterceptor<Injective_Wasmx_V1_QueryModuleStateRequest, Injective_Wasmx_V1_QueryModuleStateResponse>]
}

internal enum Injective_Wasmx_V1_QueryClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Query",
    fullName: "injective.wasmx.v1.Query",
    methods: [
      Injective_Wasmx_V1_QueryClientMetadata.Methods.wasmxParams,
      Injective_Wasmx_V1_QueryClientMetadata.Methods.contractRegistrationInfo,
      Injective_Wasmx_V1_QueryClientMetadata.Methods.wasmxModuleState,
    ]
  )

  internal enum Methods {
    internal static let wasmxParams = GRPCMethodDescriptor(
      name: "WasmxParams",
      path: "/injective.wasmx.v1.Query/WasmxParams",
      type: GRPCCallType.unary
    )

    internal static let contractRegistrationInfo = GRPCMethodDescriptor(
      name: "ContractRegistrationInfo",
      path: "/injective.wasmx.v1.Query/ContractRegistrationInfo",
      type: GRPCCallType.unary
    )

    internal static let wasmxModuleState = GRPCMethodDescriptor(
      name: "WasmxModuleState",
      path: "/injective.wasmx.v1.Query/WasmxModuleState",
      type: GRPCCallType.unary
    )
  }
}

/// Query defines the gRPC querier service.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Injective_Wasmx_V1_QueryProvider: CallHandlerProvider {
  var interceptors: Injective_Wasmx_V1_QueryServerInterceptorFactoryProtocol? { get }

  /// Retrieves wasmx params
  func wasmxParams(request: Injective_Wasmx_V1_QueryWasmxParamsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Injective_Wasmx_V1_QueryWasmxParamsResponse>

  /// Retrieves contract registration info
  func contractRegistrationInfo(request: Injective_Wasmx_V1_QueryContractRegistrationInfoRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Injective_Wasmx_V1_QueryContractRegistrationInfoResponse>

  /// Retrieves the entire wasmx module's state
  func wasmxModuleState(request: Injective_Wasmx_V1_QueryModuleStateRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Injective_Wasmx_V1_QueryModuleStateResponse>
}

extension Injective_Wasmx_V1_QueryProvider {
  internal var serviceName: Substring {
    return Injective_Wasmx_V1_QueryServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "WasmxParams":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Injective_Wasmx_V1_QueryWasmxParamsRequest>(),
        responseSerializer: ProtobufSerializer<Injective_Wasmx_V1_QueryWasmxParamsResponse>(),
        interceptors: self.interceptors?.makeWasmxParamsInterceptors() ?? [],
        userFunction: self.wasmxParams(request:context:)
      )

    case "ContractRegistrationInfo":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Injective_Wasmx_V1_QueryContractRegistrationInfoRequest>(),
        responseSerializer: ProtobufSerializer<Injective_Wasmx_V1_QueryContractRegistrationInfoResponse>(),
        interceptors: self.interceptors?.makeContractRegistrationInfoInterceptors() ?? [],
        userFunction: self.contractRegistrationInfo(request:context:)
      )

    case "WasmxModuleState":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Injective_Wasmx_V1_QueryModuleStateRequest>(),
        responseSerializer: ProtobufSerializer<Injective_Wasmx_V1_QueryModuleStateResponse>(),
        interceptors: self.interceptors?.makeWasmxModuleStateInterceptors() ?? [],
        userFunction: self.wasmxModuleState(request:context:)
      )

    default:
      return nil
    }
  }
}

/// Query defines the gRPC querier service.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Injective_Wasmx_V1_QueryAsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Injective_Wasmx_V1_QueryServerInterceptorFactoryProtocol? { get }

  /// Retrieves wasmx params
  @Sendable func wasmxParams(
    request: Injective_Wasmx_V1_QueryWasmxParamsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Injective_Wasmx_V1_QueryWasmxParamsResponse

  /// Retrieves contract registration info
  @Sendable func contractRegistrationInfo(
    request: Injective_Wasmx_V1_QueryContractRegistrationInfoRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Injective_Wasmx_V1_QueryContractRegistrationInfoResponse

  /// Retrieves the entire wasmx module's state
  @Sendable func wasmxModuleState(
    request: Injective_Wasmx_V1_QueryModuleStateRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Injective_Wasmx_V1_QueryModuleStateResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Injective_Wasmx_V1_QueryAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Injective_Wasmx_V1_QueryServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Injective_Wasmx_V1_QueryServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Injective_Wasmx_V1_QueryServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "WasmxParams":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Injective_Wasmx_V1_QueryWasmxParamsRequest>(),
        responseSerializer: ProtobufSerializer<Injective_Wasmx_V1_QueryWasmxParamsResponse>(),
        interceptors: self.interceptors?.makeWasmxParamsInterceptors() ?? [],
        wrapping: self.wasmxParams(request:context:)
      )

    case "ContractRegistrationInfo":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Injective_Wasmx_V1_QueryContractRegistrationInfoRequest>(),
        responseSerializer: ProtobufSerializer<Injective_Wasmx_V1_QueryContractRegistrationInfoResponse>(),
        interceptors: self.interceptors?.makeContractRegistrationInfoInterceptors() ?? [],
        wrapping: self.contractRegistrationInfo(request:context:)
      )

    case "WasmxModuleState":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Injective_Wasmx_V1_QueryModuleStateRequest>(),
        responseSerializer: ProtobufSerializer<Injective_Wasmx_V1_QueryModuleStateResponse>(),
        interceptors: self.interceptors?.makeWasmxModuleStateInterceptors() ?? [],
        wrapping: self.wasmxModuleState(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Injective_Wasmx_V1_QueryServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'wasmxParams'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeWasmxParamsInterceptors() -> [ServerInterceptor<Injective_Wasmx_V1_QueryWasmxParamsRequest, Injective_Wasmx_V1_QueryWasmxParamsResponse>]

  /// - Returns: Interceptors to use when handling 'contractRegistrationInfo'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeContractRegistrationInfoInterceptors() -> [ServerInterceptor<Injective_Wasmx_V1_QueryContractRegistrationInfoRequest, Injective_Wasmx_V1_QueryContractRegistrationInfoResponse>]

  /// - Returns: Interceptors to use when handling 'wasmxModuleState'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeWasmxModuleStateInterceptors() -> [ServerInterceptor<Injective_Wasmx_V1_QueryModuleStateRequest, Injective_Wasmx_V1_QueryModuleStateResponse>]
}

internal enum Injective_Wasmx_V1_QueryServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Query",
    fullName: "injective.wasmx.v1.Query",
    methods: [
      Injective_Wasmx_V1_QueryServerMetadata.Methods.wasmxParams,
      Injective_Wasmx_V1_QueryServerMetadata.Methods.contractRegistrationInfo,
      Injective_Wasmx_V1_QueryServerMetadata.Methods.wasmxModuleState,
    ]
  )

  internal enum Methods {
    internal static let wasmxParams = GRPCMethodDescriptor(
      name: "WasmxParams",
      path: "/injective.wasmx.v1.Query/WasmxParams",
      type: GRPCCallType.unary
    )

    internal static let contractRegistrationInfo = GRPCMethodDescriptor(
      name: "ContractRegistrationInfo",
      path: "/injective.wasmx.v1.Query/ContractRegistrationInfo",
      type: GRPCCallType.unary
    )

    internal static let wasmxModuleState = GRPCMethodDescriptor(
      name: "WasmxModuleState",
      path: "/injective.wasmx.v1.Query/WasmxModuleState",
      type: GRPCCallType.unary
    )
  }
}
