//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: stride/mint/v1beta1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Query provides defines the gRPC querier service.
///
/// Usage: instantiate `Stride_Mint_V1beta1_QueryClient`, then call methods of this protocol to make API calls.
internal protocol Stride_Mint_V1beta1_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Stride_Mint_V1beta1_QueryClientInterceptorFactoryProtocol? { get }

  func params(
    _ request: Stride_Mint_V1beta1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Stride_Mint_V1beta1_QueryParamsRequest, Stride_Mint_V1beta1_QueryParamsResponse>

  func epochProvisions(
    _ request: Stride_Mint_V1beta1_QueryEpochProvisionsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Stride_Mint_V1beta1_QueryEpochProvisionsRequest, Stride_Mint_V1beta1_QueryEpochProvisionsResponse>
}

extension Stride_Mint_V1beta1_QueryClientProtocol {
  internal var serviceName: String {
    return "stride.mint.v1beta1.Query"
  }

  /// Params returns the total set of minting parameters.
  ///
  /// - Parameters:
  ///   - request: Request to send to Params.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func params(
    _ request: Stride_Mint_V1beta1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Stride_Mint_V1beta1_QueryParamsRequest, Stride_Mint_V1beta1_QueryParamsResponse> {
    return self.makeUnaryCall(
      path: Stride_Mint_V1beta1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  /// EpochProvisions current minting epoch provisions value.
  ///
  /// - Parameters:
  ///   - request: Request to send to EpochProvisions.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func epochProvisions(
    _ request: Stride_Mint_V1beta1_QueryEpochProvisionsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Stride_Mint_V1beta1_QueryEpochProvisionsRequest, Stride_Mint_V1beta1_QueryEpochProvisionsResponse> {
    return self.makeUnaryCall(
      path: Stride_Mint_V1beta1_QueryClientMetadata.Methods.epochProvisions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEpochProvisionsInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Stride_Mint_V1beta1_QueryClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Stride_Mint_V1beta1_QueryNIOClient")
internal final class Stride_Mint_V1beta1_QueryClient: Stride_Mint_V1beta1_QueryClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Stride_Mint_V1beta1_QueryClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Stride_Mint_V1beta1_QueryClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the stride.mint.v1beta1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Stride_Mint_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Stride_Mint_V1beta1_QueryNIOClient: Stride_Mint_V1beta1_QueryClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Stride_Mint_V1beta1_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the stride.mint.v1beta1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Stride_Mint_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Query provides defines the gRPC querier service.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Stride_Mint_V1beta1_QueryAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Stride_Mint_V1beta1_QueryClientInterceptorFactoryProtocol? { get }

  func makeParamsCall(
    _ request: Stride_Mint_V1beta1_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Stride_Mint_V1beta1_QueryParamsRequest, Stride_Mint_V1beta1_QueryParamsResponse>

  func makeEpochProvisionsCall(
    _ request: Stride_Mint_V1beta1_QueryEpochProvisionsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Stride_Mint_V1beta1_QueryEpochProvisionsRequest, Stride_Mint_V1beta1_QueryEpochProvisionsResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Stride_Mint_V1beta1_QueryAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Stride_Mint_V1beta1_QueryClientMetadata.serviceDescriptor
  }

  internal var interceptors: Stride_Mint_V1beta1_QueryClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeParamsCall(
    _ request: Stride_Mint_V1beta1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Stride_Mint_V1beta1_QueryParamsRequest, Stride_Mint_V1beta1_QueryParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Stride_Mint_V1beta1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  internal func makeEpochProvisionsCall(
    _ request: Stride_Mint_V1beta1_QueryEpochProvisionsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Stride_Mint_V1beta1_QueryEpochProvisionsRequest, Stride_Mint_V1beta1_QueryEpochProvisionsResponse> {
    return self.makeAsyncUnaryCall(
      path: Stride_Mint_V1beta1_QueryClientMetadata.Methods.epochProvisions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEpochProvisionsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Stride_Mint_V1beta1_QueryAsyncClientProtocol {
  internal func params(
    _ request: Stride_Mint_V1beta1_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Stride_Mint_V1beta1_QueryParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Stride_Mint_V1beta1_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  internal func epochProvisions(
    _ request: Stride_Mint_V1beta1_QueryEpochProvisionsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Stride_Mint_V1beta1_QueryEpochProvisionsResponse {
    return try await self.performAsyncUnaryCall(
      path: Stride_Mint_V1beta1_QueryClientMetadata.Methods.epochProvisions.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEpochProvisionsInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Stride_Mint_V1beta1_QueryAsyncClient: Stride_Mint_V1beta1_QueryAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Stride_Mint_V1beta1_QueryClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Stride_Mint_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Stride_Mint_V1beta1_QueryClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'params'.
  func makeParamsInterceptors() -> [ClientInterceptor<Stride_Mint_V1beta1_QueryParamsRequest, Stride_Mint_V1beta1_QueryParamsResponse>]

  /// - Returns: Interceptors to use when invoking 'epochProvisions'.
  func makeEpochProvisionsInterceptors() -> [ClientInterceptor<Stride_Mint_V1beta1_QueryEpochProvisionsRequest, Stride_Mint_V1beta1_QueryEpochProvisionsResponse>]
}

internal enum Stride_Mint_V1beta1_QueryClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Query",
    fullName: "stride.mint.v1beta1.Query",
    methods: [
      Stride_Mint_V1beta1_QueryClientMetadata.Methods.params,
      Stride_Mint_V1beta1_QueryClientMetadata.Methods.epochProvisions,
    ]
  )

  internal enum Methods {
    internal static let params = GRPCMethodDescriptor(
      name: "Params",
      path: "/stride.mint.v1beta1.Query/Params",
      type: GRPCCallType.unary
    )

    internal static let epochProvisions = GRPCMethodDescriptor(
      name: "EpochProvisions",
      path: "/stride.mint.v1beta1.Query/EpochProvisions",
      type: GRPCCallType.unary
    )
  }
}

/// Query provides defines the gRPC querier service.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Stride_Mint_V1beta1_QueryProvider: CallHandlerProvider {
  var interceptors: Stride_Mint_V1beta1_QueryServerInterceptorFactoryProtocol? { get }

  /// Params returns the total set of minting parameters.
  func params(request: Stride_Mint_V1beta1_QueryParamsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Stride_Mint_V1beta1_QueryParamsResponse>

  /// EpochProvisions current minting epoch provisions value.
  func epochProvisions(request: Stride_Mint_V1beta1_QueryEpochProvisionsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Stride_Mint_V1beta1_QueryEpochProvisionsResponse>
}

extension Stride_Mint_V1beta1_QueryProvider {
  internal var serviceName: Substring {
    return Stride_Mint_V1beta1_QueryServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Params":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Mint_V1beta1_QueryParamsRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Mint_V1beta1_QueryParamsResponse>(),
        interceptors: self.interceptors?.makeParamsInterceptors() ?? [],
        userFunction: self.params(request:context:)
      )

    case "EpochProvisions":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Mint_V1beta1_QueryEpochProvisionsRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Mint_V1beta1_QueryEpochProvisionsResponse>(),
        interceptors: self.interceptors?.makeEpochProvisionsInterceptors() ?? [],
        userFunction: self.epochProvisions(request:context:)
      )

    default:
      return nil
    }
  }
}

/// Query provides defines the gRPC querier service.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Stride_Mint_V1beta1_QueryAsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Stride_Mint_V1beta1_QueryServerInterceptorFactoryProtocol? { get }

  /// Params returns the total set of minting parameters.
  @Sendable func params(
    request: Stride_Mint_V1beta1_QueryParamsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Stride_Mint_V1beta1_QueryParamsResponse

  /// EpochProvisions current minting epoch provisions value.
  @Sendable func epochProvisions(
    request: Stride_Mint_V1beta1_QueryEpochProvisionsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Stride_Mint_V1beta1_QueryEpochProvisionsResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Stride_Mint_V1beta1_QueryAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Stride_Mint_V1beta1_QueryServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Stride_Mint_V1beta1_QueryServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Stride_Mint_V1beta1_QueryServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Params":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Mint_V1beta1_QueryParamsRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Mint_V1beta1_QueryParamsResponse>(),
        interceptors: self.interceptors?.makeParamsInterceptors() ?? [],
        wrapping: self.params(request:context:)
      )

    case "EpochProvisions":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Mint_V1beta1_QueryEpochProvisionsRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Mint_V1beta1_QueryEpochProvisionsResponse>(),
        interceptors: self.interceptors?.makeEpochProvisionsInterceptors() ?? [],
        wrapping: self.epochProvisions(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Stride_Mint_V1beta1_QueryServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'params'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeParamsInterceptors() -> [ServerInterceptor<Stride_Mint_V1beta1_QueryParamsRequest, Stride_Mint_V1beta1_QueryParamsResponse>]

  /// - Returns: Interceptors to use when handling 'epochProvisions'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeEpochProvisionsInterceptors() -> [ServerInterceptor<Stride_Mint_V1beta1_QueryEpochProvisionsRequest, Stride_Mint_V1beta1_QueryEpochProvisionsResponse>]
}

internal enum Stride_Mint_V1beta1_QueryServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Query",
    fullName: "stride.mint.v1beta1.Query",
    methods: [
      Stride_Mint_V1beta1_QueryServerMetadata.Methods.params,
      Stride_Mint_V1beta1_QueryServerMetadata.Methods.epochProvisions,
    ]
  )

  internal enum Methods {
    internal static let params = GRPCMethodDescriptor(
      name: "Params",
      path: "/stride.mint.v1beta1.Query/Params",
      type: GRPCCallType.unary
    )

    internal static let epochProvisions = GRPCMethodDescriptor(
      name: "EpochProvisions",
      path: "/stride.mint.v1beta1.Query/EpochProvisions",
      type: GRPCCallType.unary
    )
  }
}
