//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: stride/records/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Query defines the gRPC querier service.
///
/// Usage: instantiate `Stride_Records_QueryClient`, then call methods of this protocol to make API calls.
internal protocol Stride_Records_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Stride_Records_QueryClientInterceptorFactoryProtocol? { get }

  func params(
    _ request: Stride_Records_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Stride_Records_QueryParamsRequest, Stride_Records_QueryParamsResponse>

  func userRedemptionRecord(
    _ request: Stride_Records_QueryGetUserRedemptionRecordRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Stride_Records_QueryGetUserRedemptionRecordRequest, Stride_Records_QueryGetUserRedemptionRecordResponse>

  func userRedemptionRecordAll(
    _ request: Stride_Records_QueryAllUserRedemptionRecordRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Stride_Records_QueryAllUserRedemptionRecordRequest, Stride_Records_QueryAllUserRedemptionRecordResponse>

  func userRedemptionRecordForUser(
    _ request: Stride_Records_QueryAllUserRedemptionRecordForUserRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Stride_Records_QueryAllUserRedemptionRecordForUserRequest, Stride_Records_QueryAllUserRedemptionRecordForUserResponse>

  func epochUnbondingRecord(
    _ request: Stride_Records_QueryGetEpochUnbondingRecordRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Stride_Records_QueryGetEpochUnbondingRecordRequest, Stride_Records_QueryGetEpochUnbondingRecordResponse>

  func epochUnbondingRecordAll(
    _ request: Stride_Records_QueryAllEpochUnbondingRecordRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Stride_Records_QueryAllEpochUnbondingRecordRequest, Stride_Records_QueryAllEpochUnbondingRecordResponse>

  func depositRecord(
    _ request: Stride_Records_QueryGetDepositRecordRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Stride_Records_QueryGetDepositRecordRequest, Stride_Records_QueryGetDepositRecordResponse>

  func depositRecordAll(
    _ request: Stride_Records_QueryAllDepositRecordRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Stride_Records_QueryAllDepositRecordRequest, Stride_Records_QueryAllDepositRecordResponse>

  func depositRecordByHost(
    _ request: Stride_Records_QueryDepositRecordByHostRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Stride_Records_QueryDepositRecordByHostRequest, Stride_Records_QueryDepositRecordByHostResponse>
}

extension Stride_Records_QueryClientProtocol {
  internal var serviceName: String {
    return "stride.records.Query"
  }

  /// Parameters queries the parameters of the module.
  ///
  /// - Parameters:
  ///   - request: Request to send to Params.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func params(
    _ request: Stride_Records_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Stride_Records_QueryParamsRequest, Stride_Records_QueryParamsResponse> {
    return self.makeUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  /// Queries a UserRedemptionRecord by id.
  ///
  /// - Parameters:
  ///   - request: Request to send to UserRedemptionRecord.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func userRedemptionRecord(
    _ request: Stride_Records_QueryGetUserRedemptionRecordRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Stride_Records_QueryGetUserRedemptionRecordRequest, Stride_Records_QueryGetUserRedemptionRecordResponse> {
    return self.makeUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.userRedemptionRecord.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUserRedemptionRecordInterceptors() ?? []
    )
  }

  /// Queries a list of UserRedemptionRecord items.
  ///
  /// - Parameters:
  ///   - request: Request to send to UserRedemptionRecordAll.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func userRedemptionRecordAll(
    _ request: Stride_Records_QueryAllUserRedemptionRecordRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Stride_Records_QueryAllUserRedemptionRecordRequest, Stride_Records_QueryAllUserRedemptionRecordResponse> {
    return self.makeUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.userRedemptionRecordAll.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUserRedemptionRecordAllInterceptors() ?? []
    )
  }

  /// Queries a list of UserRedemptionRecord items by chainId / userId pair.
  ///
  /// - Parameters:
  ///   - request: Request to send to UserRedemptionRecordForUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func userRedemptionRecordForUser(
    _ request: Stride_Records_QueryAllUserRedemptionRecordForUserRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Stride_Records_QueryAllUserRedemptionRecordForUserRequest, Stride_Records_QueryAllUserRedemptionRecordForUserResponse> {
    return self.makeUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.userRedemptionRecordForUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUserRedemptionRecordForUserInterceptors() ?? []
    )
  }

  /// Queries a EpochUnbondingRecord by id.
  ///
  /// - Parameters:
  ///   - request: Request to send to EpochUnbondingRecord.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func epochUnbondingRecord(
    _ request: Stride_Records_QueryGetEpochUnbondingRecordRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Stride_Records_QueryGetEpochUnbondingRecordRequest, Stride_Records_QueryGetEpochUnbondingRecordResponse> {
    return self.makeUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.epochUnbondingRecord.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEpochUnbondingRecordInterceptors() ?? []
    )
  }

  /// Queries a list of EpochUnbondingRecord items.
  ///
  /// - Parameters:
  ///   - request: Request to send to EpochUnbondingRecordAll.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func epochUnbondingRecordAll(
    _ request: Stride_Records_QueryAllEpochUnbondingRecordRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Stride_Records_QueryAllEpochUnbondingRecordRequest, Stride_Records_QueryAllEpochUnbondingRecordResponse> {
    return self.makeUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.epochUnbondingRecordAll.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEpochUnbondingRecordAllInterceptors() ?? []
    )
  }

  /// Queries a DepositRecord by id.
  ///
  /// - Parameters:
  ///   - request: Request to send to DepositRecord.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func depositRecord(
    _ request: Stride_Records_QueryGetDepositRecordRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Stride_Records_QueryGetDepositRecordRequest, Stride_Records_QueryGetDepositRecordResponse> {
    return self.makeUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.depositRecord.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDepositRecordInterceptors() ?? []
    )
  }

  /// Queries a list of DepositRecord items.
  ///
  /// - Parameters:
  ///   - request: Request to send to DepositRecordAll.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func depositRecordAll(
    _ request: Stride_Records_QueryAllDepositRecordRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Stride_Records_QueryAllDepositRecordRequest, Stride_Records_QueryAllDepositRecordResponse> {
    return self.makeUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.depositRecordAll.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDepositRecordAllInterceptors() ?? []
    )
  }

  /// Queries a list of DepositRecord items for a given host zone
  ///
  /// - Parameters:
  ///   - request: Request to send to DepositRecordByHost.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func depositRecordByHost(
    _ request: Stride_Records_QueryDepositRecordByHostRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Stride_Records_QueryDepositRecordByHostRequest, Stride_Records_QueryDepositRecordByHostResponse> {
    return self.makeUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.depositRecordByHost.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDepositRecordByHostInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Stride_Records_QueryClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Stride_Records_QueryNIOClient")
internal final class Stride_Records_QueryClient: Stride_Records_QueryClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Stride_Records_QueryClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Stride_Records_QueryClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the stride.records.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Stride_Records_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Stride_Records_QueryNIOClient: Stride_Records_QueryClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Stride_Records_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the stride.records.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Stride_Records_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Query defines the gRPC querier service.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Stride_Records_QueryAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Stride_Records_QueryClientInterceptorFactoryProtocol? { get }

  func makeParamsCall(
    _ request: Stride_Records_QueryParamsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryParamsRequest, Stride_Records_QueryParamsResponse>

  func makeUserRedemptionRecordCall(
    _ request: Stride_Records_QueryGetUserRedemptionRecordRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryGetUserRedemptionRecordRequest, Stride_Records_QueryGetUserRedemptionRecordResponse>

  func makeUserRedemptionRecordAllCall(
    _ request: Stride_Records_QueryAllUserRedemptionRecordRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryAllUserRedemptionRecordRequest, Stride_Records_QueryAllUserRedemptionRecordResponse>

  func makeUserRedemptionRecordForUserCall(
    _ request: Stride_Records_QueryAllUserRedemptionRecordForUserRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryAllUserRedemptionRecordForUserRequest, Stride_Records_QueryAllUserRedemptionRecordForUserResponse>

  func makeEpochUnbondingRecordCall(
    _ request: Stride_Records_QueryGetEpochUnbondingRecordRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryGetEpochUnbondingRecordRequest, Stride_Records_QueryGetEpochUnbondingRecordResponse>

  func makeEpochUnbondingRecordAllCall(
    _ request: Stride_Records_QueryAllEpochUnbondingRecordRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryAllEpochUnbondingRecordRequest, Stride_Records_QueryAllEpochUnbondingRecordResponse>

  func makeDepositRecordCall(
    _ request: Stride_Records_QueryGetDepositRecordRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryGetDepositRecordRequest, Stride_Records_QueryGetDepositRecordResponse>

  func makeDepositRecordAllCall(
    _ request: Stride_Records_QueryAllDepositRecordRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryAllDepositRecordRequest, Stride_Records_QueryAllDepositRecordResponse>

  func makeDepositRecordByHostCall(
    _ request: Stride_Records_QueryDepositRecordByHostRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryDepositRecordByHostRequest, Stride_Records_QueryDepositRecordByHostResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Stride_Records_QueryAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Stride_Records_QueryClientMetadata.serviceDescriptor
  }

  internal var interceptors: Stride_Records_QueryClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeParamsCall(
    _ request: Stride_Records_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryParamsRequest, Stride_Records_QueryParamsResponse> {
    return self.makeAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  internal func makeUserRedemptionRecordCall(
    _ request: Stride_Records_QueryGetUserRedemptionRecordRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryGetUserRedemptionRecordRequest, Stride_Records_QueryGetUserRedemptionRecordResponse> {
    return self.makeAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.userRedemptionRecord.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUserRedemptionRecordInterceptors() ?? []
    )
  }

  internal func makeUserRedemptionRecordAllCall(
    _ request: Stride_Records_QueryAllUserRedemptionRecordRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryAllUserRedemptionRecordRequest, Stride_Records_QueryAllUserRedemptionRecordResponse> {
    return self.makeAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.userRedemptionRecordAll.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUserRedemptionRecordAllInterceptors() ?? []
    )
  }

  internal func makeUserRedemptionRecordForUserCall(
    _ request: Stride_Records_QueryAllUserRedemptionRecordForUserRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryAllUserRedemptionRecordForUserRequest, Stride_Records_QueryAllUserRedemptionRecordForUserResponse> {
    return self.makeAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.userRedemptionRecordForUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUserRedemptionRecordForUserInterceptors() ?? []
    )
  }

  internal func makeEpochUnbondingRecordCall(
    _ request: Stride_Records_QueryGetEpochUnbondingRecordRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryGetEpochUnbondingRecordRequest, Stride_Records_QueryGetEpochUnbondingRecordResponse> {
    return self.makeAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.epochUnbondingRecord.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEpochUnbondingRecordInterceptors() ?? []
    )
  }

  internal func makeEpochUnbondingRecordAllCall(
    _ request: Stride_Records_QueryAllEpochUnbondingRecordRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryAllEpochUnbondingRecordRequest, Stride_Records_QueryAllEpochUnbondingRecordResponse> {
    return self.makeAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.epochUnbondingRecordAll.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEpochUnbondingRecordAllInterceptors() ?? []
    )
  }

  internal func makeDepositRecordCall(
    _ request: Stride_Records_QueryGetDepositRecordRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryGetDepositRecordRequest, Stride_Records_QueryGetDepositRecordResponse> {
    return self.makeAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.depositRecord.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDepositRecordInterceptors() ?? []
    )
  }

  internal func makeDepositRecordAllCall(
    _ request: Stride_Records_QueryAllDepositRecordRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryAllDepositRecordRequest, Stride_Records_QueryAllDepositRecordResponse> {
    return self.makeAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.depositRecordAll.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDepositRecordAllInterceptors() ?? []
    )
  }

  internal func makeDepositRecordByHostCall(
    _ request: Stride_Records_QueryDepositRecordByHostRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Stride_Records_QueryDepositRecordByHostRequest, Stride_Records_QueryDepositRecordByHostResponse> {
    return self.makeAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.depositRecordByHost.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDepositRecordByHostInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Stride_Records_QueryAsyncClientProtocol {
  internal func params(
    _ request: Stride_Records_QueryParamsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Stride_Records_QueryParamsResponse {
    return try await self.performAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.params.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeParamsInterceptors() ?? []
    )
  }

  internal func userRedemptionRecord(
    _ request: Stride_Records_QueryGetUserRedemptionRecordRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Stride_Records_QueryGetUserRedemptionRecordResponse {
    return try await self.performAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.userRedemptionRecord.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUserRedemptionRecordInterceptors() ?? []
    )
  }

  internal func userRedemptionRecordAll(
    _ request: Stride_Records_QueryAllUserRedemptionRecordRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Stride_Records_QueryAllUserRedemptionRecordResponse {
    return try await self.performAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.userRedemptionRecordAll.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUserRedemptionRecordAllInterceptors() ?? []
    )
  }

  internal func userRedemptionRecordForUser(
    _ request: Stride_Records_QueryAllUserRedemptionRecordForUserRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Stride_Records_QueryAllUserRedemptionRecordForUserResponse {
    return try await self.performAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.userRedemptionRecordForUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUserRedemptionRecordForUserInterceptors() ?? []
    )
  }

  internal func epochUnbondingRecord(
    _ request: Stride_Records_QueryGetEpochUnbondingRecordRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Stride_Records_QueryGetEpochUnbondingRecordResponse {
    return try await self.performAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.epochUnbondingRecord.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEpochUnbondingRecordInterceptors() ?? []
    )
  }

  internal func epochUnbondingRecordAll(
    _ request: Stride_Records_QueryAllEpochUnbondingRecordRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Stride_Records_QueryAllEpochUnbondingRecordResponse {
    return try await self.performAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.epochUnbondingRecordAll.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEpochUnbondingRecordAllInterceptors() ?? []
    )
  }

  internal func depositRecord(
    _ request: Stride_Records_QueryGetDepositRecordRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Stride_Records_QueryGetDepositRecordResponse {
    return try await self.performAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.depositRecord.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDepositRecordInterceptors() ?? []
    )
  }

  internal func depositRecordAll(
    _ request: Stride_Records_QueryAllDepositRecordRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Stride_Records_QueryAllDepositRecordResponse {
    return try await self.performAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.depositRecordAll.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDepositRecordAllInterceptors() ?? []
    )
  }

  internal func depositRecordByHost(
    _ request: Stride_Records_QueryDepositRecordByHostRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Stride_Records_QueryDepositRecordByHostResponse {
    return try await self.performAsyncUnaryCall(
      path: Stride_Records_QueryClientMetadata.Methods.depositRecordByHost.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDepositRecordByHostInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Stride_Records_QueryAsyncClient: Stride_Records_QueryAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Stride_Records_QueryClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Stride_Records_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Stride_Records_QueryClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'params'.
  func makeParamsInterceptors() -> [ClientInterceptor<Stride_Records_QueryParamsRequest, Stride_Records_QueryParamsResponse>]

  /// - Returns: Interceptors to use when invoking 'userRedemptionRecord'.
  func makeUserRedemptionRecordInterceptors() -> [ClientInterceptor<Stride_Records_QueryGetUserRedemptionRecordRequest, Stride_Records_QueryGetUserRedemptionRecordResponse>]

  /// - Returns: Interceptors to use when invoking 'userRedemptionRecordAll'.
  func makeUserRedemptionRecordAllInterceptors() -> [ClientInterceptor<Stride_Records_QueryAllUserRedemptionRecordRequest, Stride_Records_QueryAllUserRedemptionRecordResponse>]

  /// - Returns: Interceptors to use when invoking 'userRedemptionRecordForUser'.
  func makeUserRedemptionRecordForUserInterceptors() -> [ClientInterceptor<Stride_Records_QueryAllUserRedemptionRecordForUserRequest, Stride_Records_QueryAllUserRedemptionRecordForUserResponse>]

  /// - Returns: Interceptors to use when invoking 'epochUnbondingRecord'.
  func makeEpochUnbondingRecordInterceptors() -> [ClientInterceptor<Stride_Records_QueryGetEpochUnbondingRecordRequest, Stride_Records_QueryGetEpochUnbondingRecordResponse>]

  /// - Returns: Interceptors to use when invoking 'epochUnbondingRecordAll'.
  func makeEpochUnbondingRecordAllInterceptors() -> [ClientInterceptor<Stride_Records_QueryAllEpochUnbondingRecordRequest, Stride_Records_QueryAllEpochUnbondingRecordResponse>]

  /// - Returns: Interceptors to use when invoking 'depositRecord'.
  func makeDepositRecordInterceptors() -> [ClientInterceptor<Stride_Records_QueryGetDepositRecordRequest, Stride_Records_QueryGetDepositRecordResponse>]

  /// - Returns: Interceptors to use when invoking 'depositRecordAll'.
  func makeDepositRecordAllInterceptors() -> [ClientInterceptor<Stride_Records_QueryAllDepositRecordRequest, Stride_Records_QueryAllDepositRecordResponse>]

  /// - Returns: Interceptors to use when invoking 'depositRecordByHost'.
  func makeDepositRecordByHostInterceptors() -> [ClientInterceptor<Stride_Records_QueryDepositRecordByHostRequest, Stride_Records_QueryDepositRecordByHostResponse>]
}

internal enum Stride_Records_QueryClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Query",
    fullName: "stride.records.Query",
    methods: [
      Stride_Records_QueryClientMetadata.Methods.params,
      Stride_Records_QueryClientMetadata.Methods.userRedemptionRecord,
      Stride_Records_QueryClientMetadata.Methods.userRedemptionRecordAll,
      Stride_Records_QueryClientMetadata.Methods.userRedemptionRecordForUser,
      Stride_Records_QueryClientMetadata.Methods.epochUnbondingRecord,
      Stride_Records_QueryClientMetadata.Methods.epochUnbondingRecordAll,
      Stride_Records_QueryClientMetadata.Methods.depositRecord,
      Stride_Records_QueryClientMetadata.Methods.depositRecordAll,
      Stride_Records_QueryClientMetadata.Methods.depositRecordByHost,
    ]
  )

  internal enum Methods {
    internal static let params = GRPCMethodDescriptor(
      name: "Params",
      path: "/stride.records.Query/Params",
      type: GRPCCallType.unary
    )

    internal static let userRedemptionRecord = GRPCMethodDescriptor(
      name: "UserRedemptionRecord",
      path: "/stride.records.Query/UserRedemptionRecord",
      type: GRPCCallType.unary
    )

    internal static let userRedemptionRecordAll = GRPCMethodDescriptor(
      name: "UserRedemptionRecordAll",
      path: "/stride.records.Query/UserRedemptionRecordAll",
      type: GRPCCallType.unary
    )

    internal static let userRedemptionRecordForUser = GRPCMethodDescriptor(
      name: "UserRedemptionRecordForUser",
      path: "/stride.records.Query/UserRedemptionRecordForUser",
      type: GRPCCallType.unary
    )

    internal static let epochUnbondingRecord = GRPCMethodDescriptor(
      name: "EpochUnbondingRecord",
      path: "/stride.records.Query/EpochUnbondingRecord",
      type: GRPCCallType.unary
    )

    internal static let epochUnbondingRecordAll = GRPCMethodDescriptor(
      name: "EpochUnbondingRecordAll",
      path: "/stride.records.Query/EpochUnbondingRecordAll",
      type: GRPCCallType.unary
    )

    internal static let depositRecord = GRPCMethodDescriptor(
      name: "DepositRecord",
      path: "/stride.records.Query/DepositRecord",
      type: GRPCCallType.unary
    )

    internal static let depositRecordAll = GRPCMethodDescriptor(
      name: "DepositRecordAll",
      path: "/stride.records.Query/DepositRecordAll",
      type: GRPCCallType.unary
    )

    internal static let depositRecordByHost = GRPCMethodDescriptor(
      name: "DepositRecordByHost",
      path: "/stride.records.Query/DepositRecordByHost",
      type: GRPCCallType.unary
    )
  }
}

/// Query defines the gRPC querier service.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Stride_Records_QueryProvider: CallHandlerProvider {
  var interceptors: Stride_Records_QueryServerInterceptorFactoryProtocol? { get }

  /// Parameters queries the parameters of the module.
  func params(request: Stride_Records_QueryParamsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Stride_Records_QueryParamsResponse>

  /// Queries a UserRedemptionRecord by id.
  func userRedemptionRecord(request: Stride_Records_QueryGetUserRedemptionRecordRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Stride_Records_QueryGetUserRedemptionRecordResponse>

  /// Queries a list of UserRedemptionRecord items.
  func userRedemptionRecordAll(request: Stride_Records_QueryAllUserRedemptionRecordRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Stride_Records_QueryAllUserRedemptionRecordResponse>

  /// Queries a list of UserRedemptionRecord items by chainId / userId pair.
  func userRedemptionRecordForUser(request: Stride_Records_QueryAllUserRedemptionRecordForUserRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Stride_Records_QueryAllUserRedemptionRecordForUserResponse>

  /// Queries a EpochUnbondingRecord by id.
  func epochUnbondingRecord(request: Stride_Records_QueryGetEpochUnbondingRecordRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Stride_Records_QueryGetEpochUnbondingRecordResponse>

  /// Queries a list of EpochUnbondingRecord items.
  func epochUnbondingRecordAll(request: Stride_Records_QueryAllEpochUnbondingRecordRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Stride_Records_QueryAllEpochUnbondingRecordResponse>

  /// Queries a DepositRecord by id.
  func depositRecord(request: Stride_Records_QueryGetDepositRecordRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Stride_Records_QueryGetDepositRecordResponse>

  /// Queries a list of DepositRecord items.
  func depositRecordAll(request: Stride_Records_QueryAllDepositRecordRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Stride_Records_QueryAllDepositRecordResponse>

  /// Queries a list of DepositRecord items for a given host zone
  func depositRecordByHost(request: Stride_Records_QueryDepositRecordByHostRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Stride_Records_QueryDepositRecordByHostResponse>
}

extension Stride_Records_QueryProvider {
  internal var serviceName: Substring {
    return Stride_Records_QueryServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Params":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryParamsRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryParamsResponse>(),
        interceptors: self.interceptors?.makeParamsInterceptors() ?? [],
        userFunction: self.params(request:context:)
      )

    case "UserRedemptionRecord":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryGetUserRedemptionRecordRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryGetUserRedemptionRecordResponse>(),
        interceptors: self.interceptors?.makeUserRedemptionRecordInterceptors() ?? [],
        userFunction: self.userRedemptionRecord(request:context:)
      )

    case "UserRedemptionRecordAll":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryAllUserRedemptionRecordRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryAllUserRedemptionRecordResponse>(),
        interceptors: self.interceptors?.makeUserRedemptionRecordAllInterceptors() ?? [],
        userFunction: self.userRedemptionRecordAll(request:context:)
      )

    case "UserRedemptionRecordForUser":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryAllUserRedemptionRecordForUserRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryAllUserRedemptionRecordForUserResponse>(),
        interceptors: self.interceptors?.makeUserRedemptionRecordForUserInterceptors() ?? [],
        userFunction: self.userRedemptionRecordForUser(request:context:)
      )

    case "EpochUnbondingRecord":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryGetEpochUnbondingRecordRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryGetEpochUnbondingRecordResponse>(),
        interceptors: self.interceptors?.makeEpochUnbondingRecordInterceptors() ?? [],
        userFunction: self.epochUnbondingRecord(request:context:)
      )

    case "EpochUnbondingRecordAll":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryAllEpochUnbondingRecordRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryAllEpochUnbondingRecordResponse>(),
        interceptors: self.interceptors?.makeEpochUnbondingRecordAllInterceptors() ?? [],
        userFunction: self.epochUnbondingRecordAll(request:context:)
      )

    case "DepositRecord":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryGetDepositRecordRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryGetDepositRecordResponse>(),
        interceptors: self.interceptors?.makeDepositRecordInterceptors() ?? [],
        userFunction: self.depositRecord(request:context:)
      )

    case "DepositRecordAll":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryAllDepositRecordRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryAllDepositRecordResponse>(),
        interceptors: self.interceptors?.makeDepositRecordAllInterceptors() ?? [],
        userFunction: self.depositRecordAll(request:context:)
      )

    case "DepositRecordByHost":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryDepositRecordByHostRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryDepositRecordByHostResponse>(),
        interceptors: self.interceptors?.makeDepositRecordByHostInterceptors() ?? [],
        userFunction: self.depositRecordByHost(request:context:)
      )

    default:
      return nil
    }
  }
}

/// Query defines the gRPC querier service.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Stride_Records_QueryAsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Stride_Records_QueryServerInterceptorFactoryProtocol? { get }

  /// Parameters queries the parameters of the module.
  @Sendable func params(
    request: Stride_Records_QueryParamsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Stride_Records_QueryParamsResponse

  /// Queries a UserRedemptionRecord by id.
  @Sendable func userRedemptionRecord(
    request: Stride_Records_QueryGetUserRedemptionRecordRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Stride_Records_QueryGetUserRedemptionRecordResponse

  /// Queries a list of UserRedemptionRecord items.
  @Sendable func userRedemptionRecordAll(
    request: Stride_Records_QueryAllUserRedemptionRecordRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Stride_Records_QueryAllUserRedemptionRecordResponse

  /// Queries a list of UserRedemptionRecord items by chainId / userId pair.
  @Sendable func userRedemptionRecordForUser(
    request: Stride_Records_QueryAllUserRedemptionRecordForUserRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Stride_Records_QueryAllUserRedemptionRecordForUserResponse

  /// Queries a EpochUnbondingRecord by id.
  @Sendable func epochUnbondingRecord(
    request: Stride_Records_QueryGetEpochUnbondingRecordRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Stride_Records_QueryGetEpochUnbondingRecordResponse

  /// Queries a list of EpochUnbondingRecord items.
  @Sendable func epochUnbondingRecordAll(
    request: Stride_Records_QueryAllEpochUnbondingRecordRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Stride_Records_QueryAllEpochUnbondingRecordResponse

  /// Queries a DepositRecord by id.
  @Sendable func depositRecord(
    request: Stride_Records_QueryGetDepositRecordRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Stride_Records_QueryGetDepositRecordResponse

  /// Queries a list of DepositRecord items.
  @Sendable func depositRecordAll(
    request: Stride_Records_QueryAllDepositRecordRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Stride_Records_QueryAllDepositRecordResponse

  /// Queries a list of DepositRecord items for a given host zone
  @Sendable func depositRecordByHost(
    request: Stride_Records_QueryDepositRecordByHostRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Stride_Records_QueryDepositRecordByHostResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Stride_Records_QueryAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Stride_Records_QueryServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Stride_Records_QueryServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Stride_Records_QueryServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Params":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryParamsRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryParamsResponse>(),
        interceptors: self.interceptors?.makeParamsInterceptors() ?? [],
        wrapping: self.params(request:context:)
      )

    case "UserRedemptionRecord":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryGetUserRedemptionRecordRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryGetUserRedemptionRecordResponse>(),
        interceptors: self.interceptors?.makeUserRedemptionRecordInterceptors() ?? [],
        wrapping: self.userRedemptionRecord(request:context:)
      )

    case "UserRedemptionRecordAll":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryAllUserRedemptionRecordRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryAllUserRedemptionRecordResponse>(),
        interceptors: self.interceptors?.makeUserRedemptionRecordAllInterceptors() ?? [],
        wrapping: self.userRedemptionRecordAll(request:context:)
      )

    case "UserRedemptionRecordForUser":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryAllUserRedemptionRecordForUserRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryAllUserRedemptionRecordForUserResponse>(),
        interceptors: self.interceptors?.makeUserRedemptionRecordForUserInterceptors() ?? [],
        wrapping: self.userRedemptionRecordForUser(request:context:)
      )

    case "EpochUnbondingRecord":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryGetEpochUnbondingRecordRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryGetEpochUnbondingRecordResponse>(),
        interceptors: self.interceptors?.makeEpochUnbondingRecordInterceptors() ?? [],
        wrapping: self.epochUnbondingRecord(request:context:)
      )

    case "EpochUnbondingRecordAll":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryAllEpochUnbondingRecordRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryAllEpochUnbondingRecordResponse>(),
        interceptors: self.interceptors?.makeEpochUnbondingRecordAllInterceptors() ?? [],
        wrapping: self.epochUnbondingRecordAll(request:context:)
      )

    case "DepositRecord":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryGetDepositRecordRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryGetDepositRecordResponse>(),
        interceptors: self.interceptors?.makeDepositRecordInterceptors() ?? [],
        wrapping: self.depositRecord(request:context:)
      )

    case "DepositRecordAll":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryAllDepositRecordRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryAllDepositRecordResponse>(),
        interceptors: self.interceptors?.makeDepositRecordAllInterceptors() ?? [],
        wrapping: self.depositRecordAll(request:context:)
      )

    case "DepositRecordByHost":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Stride_Records_QueryDepositRecordByHostRequest>(),
        responseSerializer: ProtobufSerializer<Stride_Records_QueryDepositRecordByHostResponse>(),
        interceptors: self.interceptors?.makeDepositRecordByHostInterceptors() ?? [],
        wrapping: self.depositRecordByHost(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Stride_Records_QueryServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'params'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeParamsInterceptors() -> [ServerInterceptor<Stride_Records_QueryParamsRequest, Stride_Records_QueryParamsResponse>]

  /// - Returns: Interceptors to use when handling 'userRedemptionRecord'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUserRedemptionRecordInterceptors() -> [ServerInterceptor<Stride_Records_QueryGetUserRedemptionRecordRequest, Stride_Records_QueryGetUserRedemptionRecordResponse>]

  /// - Returns: Interceptors to use when handling 'userRedemptionRecordAll'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUserRedemptionRecordAllInterceptors() -> [ServerInterceptor<Stride_Records_QueryAllUserRedemptionRecordRequest, Stride_Records_QueryAllUserRedemptionRecordResponse>]

  /// - Returns: Interceptors to use when handling 'userRedemptionRecordForUser'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUserRedemptionRecordForUserInterceptors() -> [ServerInterceptor<Stride_Records_QueryAllUserRedemptionRecordForUserRequest, Stride_Records_QueryAllUserRedemptionRecordForUserResponse>]

  /// - Returns: Interceptors to use when handling 'epochUnbondingRecord'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeEpochUnbondingRecordInterceptors() -> [ServerInterceptor<Stride_Records_QueryGetEpochUnbondingRecordRequest, Stride_Records_QueryGetEpochUnbondingRecordResponse>]

  /// - Returns: Interceptors to use when handling 'epochUnbondingRecordAll'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeEpochUnbondingRecordAllInterceptors() -> [ServerInterceptor<Stride_Records_QueryAllEpochUnbondingRecordRequest, Stride_Records_QueryAllEpochUnbondingRecordResponse>]

  /// - Returns: Interceptors to use when handling 'depositRecord'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDepositRecordInterceptors() -> [ServerInterceptor<Stride_Records_QueryGetDepositRecordRequest, Stride_Records_QueryGetDepositRecordResponse>]

  /// - Returns: Interceptors to use when handling 'depositRecordAll'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDepositRecordAllInterceptors() -> [ServerInterceptor<Stride_Records_QueryAllDepositRecordRequest, Stride_Records_QueryAllDepositRecordResponse>]

  /// - Returns: Interceptors to use when handling 'depositRecordByHost'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDepositRecordByHostInterceptors() -> [ServerInterceptor<Stride_Records_QueryDepositRecordByHostRequest, Stride_Records_QueryDepositRecordByHostResponse>]
}

internal enum Stride_Records_QueryServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Query",
    fullName: "stride.records.Query",
    methods: [
      Stride_Records_QueryServerMetadata.Methods.params,
      Stride_Records_QueryServerMetadata.Methods.userRedemptionRecord,
      Stride_Records_QueryServerMetadata.Methods.userRedemptionRecordAll,
      Stride_Records_QueryServerMetadata.Methods.userRedemptionRecordForUser,
      Stride_Records_QueryServerMetadata.Methods.epochUnbondingRecord,
      Stride_Records_QueryServerMetadata.Methods.epochUnbondingRecordAll,
      Stride_Records_QueryServerMetadata.Methods.depositRecord,
      Stride_Records_QueryServerMetadata.Methods.depositRecordAll,
      Stride_Records_QueryServerMetadata.Methods.depositRecordByHost,
    ]
  )

  internal enum Methods {
    internal static let params = GRPCMethodDescriptor(
      name: "Params",
      path: "/stride.records.Query/Params",
      type: GRPCCallType.unary
    )

    internal static let userRedemptionRecord = GRPCMethodDescriptor(
      name: "UserRedemptionRecord",
      path: "/stride.records.Query/UserRedemptionRecord",
      type: GRPCCallType.unary
    )

    internal static let userRedemptionRecordAll = GRPCMethodDescriptor(
      name: "UserRedemptionRecordAll",
      path: "/stride.records.Query/UserRedemptionRecordAll",
      type: GRPCCallType.unary
    )

    internal static let userRedemptionRecordForUser = GRPCMethodDescriptor(
      name: "UserRedemptionRecordForUser",
      path: "/stride.records.Query/UserRedemptionRecordForUser",
      type: GRPCCallType.unary
    )

    internal static let epochUnbondingRecord = GRPCMethodDescriptor(
      name: "EpochUnbondingRecord",
      path: "/stride.records.Query/EpochUnbondingRecord",
      type: GRPCCallType.unary
    )

    internal static let epochUnbondingRecordAll = GRPCMethodDescriptor(
      name: "EpochUnbondingRecordAll",
      path: "/stride.records.Query/EpochUnbondingRecordAll",
      type: GRPCCallType.unary
    )

    internal static let depositRecord = GRPCMethodDescriptor(
      name: "DepositRecord",
      path: "/stride.records.Query/DepositRecord",
      type: GRPCCallType.unary
    )

    internal static let depositRecordAll = GRPCMethodDescriptor(
      name: "DepositRecordAll",
      path: "/stride.records.Query/DepositRecordAll",
      type: GRPCCallType.unary
    )

    internal static let depositRecordByHost = GRPCMethodDescriptor(
      name: "DepositRecordByHost",
      path: "/stride.records.Query/DepositRecordByHost",
      type: GRPCCallType.unary
    )
  }
}
