//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: persistence/interchainquery/v1beta1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Query provides defines the gRPC querier service.
///
/// Usage: instantiate `Persistence_Interchainquery_V1beta1_QuerySrvrClient`, then call methods of this protocol to make API calls.
internal protocol Persistence_Interchainquery_V1beta1_QuerySrvrClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrClientInterceptorFactoryProtocol? { get }

  func queries(
    _ request: Persistence_Interchainquery_V1beta1_QueryRequestsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Persistence_Interchainquery_V1beta1_QueryRequestsRequest, Persistence_Interchainquery_V1beta1_QueryRequestsResponse>
}

extension Persistence_Interchainquery_V1beta1_QuerySrvrClientProtocol {
  internal var serviceName: String {
    return "persistence.interchainquery.v1beta1.QuerySrvr"
  }

  /// Params returns the total set of minting parameters.
  ///
  /// - Parameters:
  ///   - request: Request to send to Queries.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func queries(
    _ request: Persistence_Interchainquery_V1beta1_QueryRequestsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Persistence_Interchainquery_V1beta1_QueryRequestsRequest, Persistence_Interchainquery_V1beta1_QueryRequestsResponse> {
    return self.makeUnaryCall(
      path: Persistence_Interchainquery_V1beta1_QuerySrvrClientMetadata.Methods.queries.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueriesInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Persistence_Interchainquery_V1beta1_QuerySrvrClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Persistence_Interchainquery_V1beta1_QuerySrvrNIOClient")
internal final class Persistence_Interchainquery_V1beta1_QuerySrvrClient: Persistence_Interchainquery_V1beta1_QuerySrvrClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the persistence.interchainquery.v1beta1.QuerySrvr service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Persistence_Interchainquery_V1beta1_QuerySrvrNIOClient: Persistence_Interchainquery_V1beta1_QuerySrvrClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrClientInterceptorFactoryProtocol?

  /// Creates a client for the persistence.interchainquery.v1beta1.QuerySrvr service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Query provides defines the gRPC querier service.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Persistence_Interchainquery_V1beta1_QuerySrvrAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrClientInterceptorFactoryProtocol? { get }

  func makeQueriesCall(
    _ request: Persistence_Interchainquery_V1beta1_QueryRequestsRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Persistence_Interchainquery_V1beta1_QueryRequestsRequest, Persistence_Interchainquery_V1beta1_QueryRequestsResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Persistence_Interchainquery_V1beta1_QuerySrvrAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Persistence_Interchainquery_V1beta1_QuerySrvrClientMetadata.serviceDescriptor
  }

  internal var interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeQueriesCall(
    _ request: Persistence_Interchainquery_V1beta1_QueryRequestsRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Persistence_Interchainquery_V1beta1_QueryRequestsRequest, Persistence_Interchainquery_V1beta1_QueryRequestsResponse> {
    return self.makeAsyncUnaryCall(
      path: Persistence_Interchainquery_V1beta1_QuerySrvrClientMetadata.Methods.queries.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueriesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Persistence_Interchainquery_V1beta1_QuerySrvrAsyncClientProtocol {
  internal func queries(
    _ request: Persistence_Interchainquery_V1beta1_QueryRequestsRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Persistence_Interchainquery_V1beta1_QueryRequestsResponse {
    return try await self.performAsyncUnaryCall(
      path: Persistence_Interchainquery_V1beta1_QuerySrvrClientMetadata.Methods.queries.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeQueriesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Persistence_Interchainquery_V1beta1_QuerySrvrAsyncClient: Persistence_Interchainquery_V1beta1_QuerySrvrAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Persistence_Interchainquery_V1beta1_QuerySrvrClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'queries'.
  func makeQueriesInterceptors() -> [ClientInterceptor<Persistence_Interchainquery_V1beta1_QueryRequestsRequest, Persistence_Interchainquery_V1beta1_QueryRequestsResponse>]
}

internal enum Persistence_Interchainquery_V1beta1_QuerySrvrClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "QuerySrvr",
    fullName: "persistence.interchainquery.v1beta1.QuerySrvr",
    methods: [
      Persistence_Interchainquery_V1beta1_QuerySrvrClientMetadata.Methods.queries,
    ]
  )

  internal enum Methods {
    internal static let queries = GRPCMethodDescriptor(
      name: "Queries",
      path: "/persistence.interchainquery.v1beta1.QuerySrvr/Queries",
      type: GRPCCallType.unary
    )
  }
}

/// Query provides defines the gRPC querier service.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Persistence_Interchainquery_V1beta1_QuerySrvrProvider: CallHandlerProvider {
  var interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrServerInterceptorFactoryProtocol? { get }

  /// Params returns the total set of minting parameters.
  func queries(request: Persistence_Interchainquery_V1beta1_QueryRequestsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Persistence_Interchainquery_V1beta1_QueryRequestsResponse>
}

extension Persistence_Interchainquery_V1beta1_QuerySrvrProvider {
  internal var serviceName: Substring {
    return Persistence_Interchainquery_V1beta1_QuerySrvrServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Queries":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Persistence_Interchainquery_V1beta1_QueryRequestsRequest>(),
        responseSerializer: ProtobufSerializer<Persistence_Interchainquery_V1beta1_QueryRequestsResponse>(),
        interceptors: self.interceptors?.makeQueriesInterceptors() ?? [],
        userFunction: self.queries(request:context:)
      )

    default:
      return nil
    }
  }
}

/// Query provides defines the gRPC querier service.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Persistence_Interchainquery_V1beta1_QuerySrvrAsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrServerInterceptorFactoryProtocol? { get }

  /// Params returns the total set of minting parameters.
  @Sendable func queries(
    request: Persistence_Interchainquery_V1beta1_QueryRequestsRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Persistence_Interchainquery_V1beta1_QueryRequestsResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Persistence_Interchainquery_V1beta1_QuerySrvrAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Persistence_Interchainquery_V1beta1_QuerySrvrServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Persistence_Interchainquery_V1beta1_QuerySrvrServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Persistence_Interchainquery_V1beta1_QuerySrvrServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Queries":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Persistence_Interchainquery_V1beta1_QueryRequestsRequest>(),
        responseSerializer: ProtobufSerializer<Persistence_Interchainquery_V1beta1_QueryRequestsResponse>(),
        interceptors: self.interceptors?.makeQueriesInterceptors() ?? [],
        wrapping: self.queries(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Persistence_Interchainquery_V1beta1_QuerySrvrServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'queries'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeQueriesInterceptors() -> [ServerInterceptor<Persistence_Interchainquery_V1beta1_QueryRequestsRequest, Persistence_Interchainquery_V1beta1_QueryRequestsResponse>]
}

internal enum Persistence_Interchainquery_V1beta1_QuerySrvrServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "QuerySrvr",
    fullName: "persistence.interchainquery.v1beta1.QuerySrvr",
    methods: [
      Persistence_Interchainquery_V1beta1_QuerySrvrServerMetadata.Methods.queries,
    ]
  )

  internal enum Methods {
    internal static let queries = GRPCMethodDescriptor(
      name: "Queries",
      path: "/persistence.interchainquery.v1beta1.QuerySrvr/Queries",
      type: GRPCCallType.unary
    )
  }
}
