// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ixo/project/genesis.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// GenesisState defines the project module's genesis state.
struct Project_GenesisState {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var projectDocs: [Project_ProjectDoc] = []

  var accountMaps: [Project_GenesisAccountMap] = []

  var withdrawalsInfos: [Project_WithdrawalInfoDocs] = []

  var claims: [Project_Claims] = []

  var params: Project_Params {
    get {return _params ?? Project_Params()}
    set {_params = newValue}
  }
  /// Returns true if `params` has been explicitly set.
  var hasParams: Bool {return self._params != nil}
  /// Clears the value of `params`. Subsequent reads from it will return its default value.
  mutating func clearParams() {self._params = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _params: Project_Params? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "project"

extension Project_GenesisState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GenesisState"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "project_docs"),
    2: .standard(proto: "account_maps"),
    3: .standard(proto: "withdrawals_infos"),
    4: .same(proto: "claims"),
    5: .same(proto: "params"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.projectDocs) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.accountMaps) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.withdrawalsInfos) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.claims) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._params) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.projectDocs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.projectDocs, fieldNumber: 1)
    }
    if !self.accountMaps.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.accountMaps, fieldNumber: 2)
    }
    if !self.withdrawalsInfos.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.withdrawalsInfos, fieldNumber: 3)
    }
    if !self.claims.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.claims, fieldNumber: 4)
    }
    if let v = self._params {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Project_GenesisState, rhs: Project_GenesisState) -> Bool {
    if lhs.projectDocs != rhs.projectDocs {return false}
    if lhs.accountMaps != rhs.accountMaps {return false}
    if lhs.withdrawalsInfos != rhs.withdrawalsInfos {return false}
    if lhs.claims != rhs.claims {return false}
    if lhs._params != rhs._params {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
